---
apiVersion: v1
kind: Service
metadata:
  name: comsumer
  labels:
    app: comsumer
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http-gin
  selector:
    app: comsumer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: comsumer-config
  labels:
    app: comsumer
data:
  log.yml: |
    level: "debug"
    development: true
    disableCaller: true
    disableStacktrace: true
    sampling:
    encoding: "console"

    # encoder
    encoderConfig:
      messageKey: "message"
      levelKey: "level"
      timeKey: "time"
      nameKey: "logger"
      callerKey: "caller"
      stacktraceKey: "stacktrace"
      lineEnding: ""
      levelEncoder: "capitalColor"
      timeEncoder: "iso8601"
      durationEncoder: "seconds"
      callerEncoder: "short"
      nameEncoder: ""

    outputPaths:
      - "stderr"
    errorOutputPaths:
      - "stderr"
    initialFields:
  client.yml: |
    # dubbo client yaml configure file
    check: true
    # client
    request_timeout : "3s"
    # connect timeout
    connect_timeout : "3s"

    # application config
    application:
      organization : "k8s.com"
      name  : "mesh demo"
      module : "mesh demo consumer client"
      version : "0.0.1"
      owner : "symcn"
      environment : "release"


    references:
      "UserProvider":
        interface : "com.k8s.User.UserProvider"
        cluster: "failover"
        url:  "dubbo://user-provider:20880"
        methods :
          - name: "GetUser"
          - name: "SetUser"
      "OrderProvider":
        interface : "com.k8s.Order.OrderProvider"
        cluster: "failover"
        url:  "dubbo://order-provider:20880"
        methods :
          - name: "GetOrder"
          - name: "SetOrder"

    protocol_conf:
      dubbo:
        reconnect_interval: 0
        connection_number: 2
        heartbeat_period: "5s"
        session_timeout: "20s"
        pool_size: 64
        pool_ttl: 600
        getty_session_param:
          compress_encoding: false
          tcp_no_delay: true
          tcp_keep_alive: true
          keep_alive_period: "120s"
          tcp_r_buf_size: 262144
          tcp_w_buf_size: 65536
          pkg_rq_size: 1024
          pkg_wq_size: 512
          tcp_read_timeout: "5s"
          tcp_write_timeout: "5s"
          wait_timeout: "1s"
          max_msg_len: 10240
          session_name: "client"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comsumer-blue
  labels:
    app: comsumer
    version: blue
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: comsumer
      version: blue
  template:
    metadata:
      labels:
        app: comsumer
        version: blue
      annotations:
        sidecar.istio.io/componentLogLevel: "stats:warning,wasm:trace,misc:error"
    spec:
      volumes:
        - name: config
          configMap:
            name: comsumer-config
            defaultMode: 420
      containers:
        - name: comsumer
          image: "symcn.tencentcloudcr.com/symcn/consumer:v0.0.4"
          args:
            - --server
            - "grpc-server:8000"
          imagePullPolicy: Always
#          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config
              mountPath: "/config"
          ports:
            - name: http
              containerPort: 8090
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.serviceAccountName
            - name: APP_LOG_CONF_FILE
              value: "/config/log.yml"
            - name: CONF_CONSUMER_FILE_PATH
              value: "/config/client.yml"
#          livenessProbe:
#            httpGet:
#              path: /live
#              port: 8080
#            initialDelaySeconds: 5
#            periodSeconds: 30
#          readinessProbe:
#            httpGet:
#              path: /ready
#              port: 8080
#            initialDelaySeconds: 5
#            periodSeconds: 30
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - comsumer
                topologyKey: kubernetes.io/hostname
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comsumer-green
  labels:
    app: comsumer
    version: green
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: comsumer
      version: green
  template:
    metadata:
      labels:
        app: comsumer
        version: green
      annotations:
        sidecar.istio.io/componentLogLevel: "stats:warning,wasm:trace,misc:error"
    spec:
      volumes:
        - name: config
          configMap:
            name: comsumer-config
            defaultMode: 420
      containers:
        - name: comsumer
          image: "symcn.tencentcloudcr.com/symcn/consumer:v0.0.4"
          args:
            - --server
            - "grpc-server:8000"
          imagePullPolicy: Always
          #          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config
              mountPath: "/config"
          ports:
            - name: http
              containerPort: 8090
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.serviceAccountName
            - name: APP_LOG_CONF_FILE
              value: "/config/log.yml"
            - name: CONF_CONSUMER_FILE_PATH
              value: "/config/client.yml"
#          livenessProbe:
#            httpGet:
#              path: /live
#              port: 8080
#            initialDelaySeconds: 5
#            periodSeconds: 30
#          readinessProbe:
#            httpGet:
#              path: /ready
#              port: 8080
#            initialDelaySeconds: 5
#            periodSeconds: 30
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - comsumer
                topologyKey: kubernetes.io/hostname
---
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: comsumer-ingress
#  labels:
#    app: comsumer
#  annotations:
#    kubernetes.io/ingress.class: traefik
#spec:
#  rules:
#    - host: td.mesh.symcn.com
#      http:
#        paths:
#          - path: /
#            backend:
#              serviceName: comsumer
#              servicePort: http-gin

